### PR TITLE
fix includes

### PR DESCRIPTION
**Pull request by uNiversaI**

### CODE REVIEW

**Comment by opdenkamp** [comment]
eeh... no? why would you want to do this?

**Comment by opdenkamp** [comment]
same with the other add-ons, why?

**Comment by uNiversaI** [comment]
well Im not going to open this again, you should speak to @wsnipex and @hudokkow and read https://github.com/xbmc/audioencoder.vorbis/commit/39fa0f4455fc272f2354b6f973f8dd8a500c3b69 for rationale

**Comment by opdenkamp** [comment]
closing was due to fat fingers and not on purpose, but this is just a big meh. guess what happens when 2 libs use the same header filename.

**Pull request closed without merging**
