### PR TITLE
Add missing fields for testing

### PR DESCRIPTION
**Pull request by emveepee**
To assist testing without a backend, add SetYear() to Recordings and EPG  and add SetEpisodePartNumber() to EPG.  

Note currently EpisodePartNumber is not exposed for skinnning.

### CODE REVIEW

**Comment by ksooo** [comment]
@emveepee closing because this cannot go into Omega.

**Comment by emveepee** [comment]
> @emveepee closing because this cannot go into Omega.

Thanks on PR 159 I noted this should be canceled I wasn't sure how.  BTW there is nothing wrong with the PR in Omega, just no way to display it.

**Comment by ksooo** [comment]
Why should we merge code of no value into the omega addon? This makes absolutely no sense.

**Comment by emveepee** [comment]
> Why should we merge code of no value into the omega addon? This makes absolutely no sense.

Agreed which is why asked for it to taken out  but it is not an absolute no.   Not all tests have to be against a skin, initially I used it to check that the database was being updated correctly.

**Pull request closed without merging**
