### PR TITLE
Change to now C++ based addon interface

### PR DESCRIPTION
**Pull request by AlwinEsch**
Change to new C++ style, see related Pull Request on Kodi:

**Stil work in progress and not ready to merge!!!**

### CODE REVIEW

**Comment by phunkyfish** [comment]
Very cool, so once ready an entire addon would need to converted in one go, so either C or C++ but not both?

**Comment by AlwinEsch** [comment]
Right, unfortunately, old "C" is not easy to integrate afterwards.

But after that it gets easier on addons itself because you get a big "C" code chain in the header. So only in one place bigger work and not at all addons.

**Comment by AlwinEsch** [comment]
Is updated and cleaned up for rework on https://github.com/xbmc/xbmc/pull/16485

**Comment by AlwinEsch** [comment]
Chart about (hope correct)
Bildschirmfoto vom 2020-05-13 01-14-17

**Pull request merged**
