### PR TITLE
Fix icon path since moved to repo

### PR DESCRIPTION
**Pull request by MikeSiLVO**
Path to icons is for old location when it was installed using Kodi installer.

Is the same for matrix version but I can do another PR if that is helpful.

EDIT: Just noticed I removed some whitespace  cause my text editor does that automatically.

I can remove that change if it is not wanted.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
This request does fix the way by addons from ZIP, but after them it no more work on a Linux OS installl where it is on `/usr/share/kodi/addons/pvr.demo/...`.

I look about a fix inside Kodi itself.

**Comment by MikeSiLVO** [comment]
@AlwinEsch Ok didn't know that, I use Windows. 

I thought [special protocol](https://kodi.wiki/view/Special_protocol) was to make it platform independent though?

**Comment by AlwinEsch** [comment]
I becomed also another idea for addon itself, wait a moment and I bring a example.

**Comment by AlwinEsch** [comment]
Here the patch about another way where work in both cases:
[0001-fix-icon-path-use.patch.txt](https://github.com/kodi-pvr/pvr.demo/files/3521974/0001-fix-icon-path-use.patch.txt)

**Comment by MikeSiLVO** [comment]
Do you want me to update this PR with those changes or will you do them instead?

The PVRDemoData.cpp C++ code changes are beyond my understanding but I can copy paste like its nobody's business 😉

**Comment by AlwinEsch** [comment]
If you like :smile:, otherwise I can create another request.

**Comment by MikeSiLVO** [comment]
@AlwinEsch Updated PR Please double check I did it correctly when you have a chance.

I will fix it if I have made a mistake 😃

**Comment by AlwinEsch** [comment]
Has it worked on Windows and icons present? If yes perfect :smile:

**Comment by MikeSiLVO** [comment]
I didn't test will do that right now.

**Comment by MikeSiLVO** [comment]
Actually I don't think I can test without it being built I don't have any of that stuff installed. Can you provide a test build?

**Comment by AlwinEsch** [comment]
No problem I start my Windows and becomes tested.

**Comment by AlwinEsch** [comment]
It works, Thanks a lot!

**Comment by MikeSiLVO** [comment]
Thank You! You are the one who actually fixed it 😉 

Should I open new PR for Matrix version?

**Comment by MikeSiLVO** [comment]
@AlwinEsch Also besides the question above does this need version bump to update those that have it already installed?

**Comment by AlwinEsch** [comment]
Yes, but you found the bug and without you, it would not be fixed (was overlooked by us).

With Matrix version, yes then also a request there.

**Comment by AlwinEsch** [comment]
@Rechi need it a version bump?

**Comment by Rechi** [comment]
If you want to that users get this changes, yes.

**Pull request merged**
